server:
  port: 2223


eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.55.195.31:3306/rate_of_flow?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    druid:
      initialSize: 10
      minIdle: 5
      maxActive: 20
      maxWait: 10
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    servlet:
      multipart:
        max-request-size: 52128880
  redis:
    port: 6379
    host: localhost
  application:
    name: user

  data:
    elasticsearch:
      cluster-nodes: localhost:9300
  rabbitmq:
    addresses: 39.105.164.189:5672
    password: 123456
    username: rabbitmq
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启下划线转驼峰
    map-underscore-to-camel-case: true

